### PR TITLE
Fix problem for overlapping primary and secondary label

### PR DESCRIPTION
**Pull request by Husseinhj**
* Fix issue #74 and #81 concerning primary and secondary label overlap when some libraries override UIView control methods.

Thanks to @hrsalehi

### CODE REVIEW

**Comment by quangctkm9207** [comment]
Thanks @Husseinhj for PR.

**Comment by Husseinhj** [comment]
Hi dear @quangctkm9207 
When do you publish v0.6.4?

**Comment by quangctkm9207** [comment]
Thanks for reminding me. 
I have just pushed it on CocoaPod.

**Comment by Husseinhj** [comment]
@quangctkm9207 Thanks 👍

**Pull request merged**
