### PR TITLE
Fix for positioning instruction view #116

### PR DESCRIPTION
**Pull request by ezefire**

### CODE REVIEW

**Comment by quangctkm9207** [comment]
Thank @ezefire for your PR. Merged it already.

**Comment by ezefire** [comment]
Hi!
Thanks for the info! I hope the changes will help.

Will you do a new release with that changes?

**Comment by quangctkm9207** [comment]
I am going to release the patch version soon.

**Comment by quangctkm9207** [comment]
@ezefire : After the changes in your last PR, now we are not able to change the background radius. It seems that the background radius is fixed at 300.  
```showcase.radius = 1000``` // Unable

**Comment by ezefire** [comment]
Hi,

I've made many tests in the code i forked from your code and effectively i
found a problem changing the radius but only on iPad. On iPhone it works
normally.
I was looking for a bug in the code but i saw that the changes i've done
where related to iPhone.

Is it possible that the problem was before my changes or that another PR
has broke that ?

I attach many screenshots from iPhone:

- Radius = 400
[image: Screen Shot 2020-04-14 at 09.41.28.png]

- Radius = 500
[image: Screen Shot 2020-04-14 at 09.38.33.png]

**Comment by ezefire** [comment]
After more tests i've found that there are no problems in iPad related to
the radius. The problem on iPad is the position of the text but not the
radius.
I add many screenshots:

- Radius : 300
[image: Simulator Screen Shot - iPad Air (3rd generation) - 2020-04-14 at
09.52.54.png]

- Radius : 400
[image: Simulator Screen Shot - iPad Air (3rd generation) - 2020-04-14 at
09.52.14.png]

- Radius : 500
[image: Simulator Screen Shot - iPad Air (3rd generation) - 2020-04-14 at
09.51.31.png]

**Comment by quangctkm9207** [comment]
I am sorry that it is not because of your changes.
The issue with iPad is still there from the past.

**Pull request merged**
