### PR TITLE
TapThrough Functionality

### PR DESCRIPTION
**Pull request by poisondminds**
Let me know if this needs more explanation.

Also, I did make changes to the sample app on my local machine to test this out, but didn't necessarily want to include them. Let me know if you'd want to see how I tested, or if you have trouble testing yourself.

### CODE REVIEW

**Comment by quangctkm9207** [comment]
Thank @poisondminds! I merged it already.

**Comment by GPryan** [comment]
Great! @quangctkm9207 would you consider making a 0.6.7 including some of the recent changes?

**Comment by quangctkm9207** [comment]
Sure @GPryan . I'm gonna release it today.

**Comment by poisondminds** [comment]
Great :) I look forward do it

**Comment by quangctkm9207** [comment]
I have just published the version '0.7.0' on CocoaPods. You can check it out.

**Comment by acali18** [comment]
I am having a problem with the tapThrough functionality of the tabBar. Allowing tapThrough on a tabBar creates the following error: 
"Directly modifying a tab bar managed by a tab bar controller is not allowed'

Here is the code I've used in the past to select a tabBar index:
self.tabBarController?.selectedIndex = 2

But here is the code in the MaterialShowcase.swift:
onTapThrough = { tabBar.selectedItem = tabBar.items?[itemIndex] }

I believe I need to pass the tabBarController somehow?

**Comment by poisondminds** [comment]
@acali18 Do you get the same error if you try to perform `tabBar.selectedItem = tabBar.items?[itemIndex]` in isolation, outside of the context of MaterialShowcase, just on its own?

Googling around, it looks like this is a common error & that tab bars shouldn't be managed directly like this. See this answer for example
https://stackoverflow.com/a/6183815/2901136

**Comment by poisondminds** [comment]
@acali18 Ah yes, it's looking like this functionality is only working properly for standalone `UITabBar` and not with a tab bar controller. Can you make another issue for this? It's likely that we'll have to supply another constructor that accepts a `UITabBarController`

**Comment by acali18** [comment]
@poisondminds - Yes, that sounds correct. I will make the new issue. I wanted to discuss it first in case I had missed something.

**Comment by acali18** [comment]
Created here: https://github.com/aromajoin/material-showcase-ios/issues/118

**Comment by petrkahanek** [comment]
Hello guys,

any news to this? I am having the same issue as @acali18 .

**Comment by imSarfaroz** [comment]
Any updates guys?

**Pull request merged**
